### ISSUE TITLE
将阿里云源默认为 https

### ISSUE THREAD

**Issue by cxlwill** [Fenghuapiao/PyQuickInstall#7]
感谢作者的制作，节省了我非常多的时间。
阿里云源默认支持 https，可否将现有源修改为 https？或者作者用 http 有深意？

**Comment by yhangf** [comment]
没有什么特别的深意，可以改的，不过据我所知阿里云默认是http，楼主所说能否给与出处。

**Comment by fanthos** [comment]
`The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.`
或者在配置文件里面信任阿里云网址
